/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsNumber,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { InventoryCreateNestedManyWithoutGadgetsInput } from "./InventoryCreateNestedManyWithoutGadgetsInput";
import { OrderCreateNestedManyWithoutGadgetsInput } from "./OrderCreateNestedManyWithoutGadgetsInput";

@InputType()
class GadgetCreateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => InventoryCreateNestedManyWithoutGadgetsInput,
  })
  @ValidateNested()
  @Type(() => InventoryCreateNestedManyWithoutGadgetsInput)
  @IsOptional()
  @Field(() => InventoryCreateNestedManyWithoutGadgetsInput, {
    nullable: true,
  })
  inventories?: InventoryCreateNestedManyWithoutGadgetsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutGadgetsInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutGadgetsInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutGadgetsInput, {
    nullable: true,
  })
  orders?: OrderCreateNestedManyWithoutGadgetsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stockQuantity?: number | null;
}

export { GadgetCreateInput as GadgetCreateInput };
